[Issue5] abstract room
patrickv83/demonata pull request #13
Opened 2018-03-09 21:26 UTC by patrickv83

2018-03-21 01:44 UTC, jalyxis55 requested changes
Room() doesn't need (x,y). I think an (x,y) will be used with player movement rather than where the room sits in the room.

2018-03-21 03:19 UTC, jalyxis55 submitted a review, later dismissed
I lied, room does have (x, y). sorry.

2018-03-21 17:48 UTC, patrickv83 commented
Coordinates are back in Room class, stub for EmptyRoom class added

2018-04-08 01:08 UTC, claudecyrill approved these changes

2018-04-08 01:08 UTC, claudecyrill commented on demonata/room.py
> +class EmptyRoom(Room):
Would need to get scrapped on merge since empty room is defined the latest pull request.

2018-04-08 01:18 UTC, merged